### ISSUE TITLE
The program can not run with Numpy 1.20.2

### ISSUE THREAD

**Issue by nooooo380** [jcrichard/pyrb#1]
When I upgrade the version of NumPy from 1.19.4 to 1.20.2, The program can not run.

**Comment by jcrichard** [comment]
Hi, can you give more details and the trace please?

**Comment by nooooo380** [comment]
----> 5 ERC.solve()

D:\Anaconda\lib\site-packages\pyrb\allocation.py in solve(self)
    125 
    126     def solve(self):
--> 127         x = solve_rb_ccd(cov=self.cov)
    128         self._x = tools.to_array(x / x.sum())
    129         self.lambda_star = self.get_volatility()

D:\Anaconda\lib\site-packages\pyrb\solvers.py in solve_rb_ccd(cov, budgets, pi, c, bounds, lambda_log, _varphi)
    134     while not cvg:
    135         x, Sx, sigma_x = _cycle(
--> 136             x, c, var, _varphi, sigma_x, Sx, budgets, pi, bounds, lambda_log, cov
    137         )
    138         cvg = np.sum(np.array(x - x0) ** 2) <= CCD_COVERGENCE_TOL

SystemError: CPUDispatcher(<function _cycle at 0x000001D22A83C048>) returned a result with an error set

**Comment by jcrichard** [comment]
I just tried on [Google colab](https://colab.research.google.com/drive/1AbgiERC1730bXUsG9V_E7kZasA8exLiX?usp=sharing) there is no issue with numpy it seems.

**Comment by nikitazhhy** [comment]
> I just tried on [Google colab](https://colab.research.google.com/drive/1AbgiERC1730bXUsG9V_E7kZasA8exLiX?usp=sharing) there is no issue with numpy it seems.


got the  same problem today:
----------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
TypeError: expected dtype object, got 'numpy.dtype[float64]'

The above exception was the direct cause of the following exception:

SystemError                               Traceback (most recent call last)
<ipython-input-20-18f3ae0b1112> in <module>()
      1 ERC = pyrb.EqualRiskContribution(covariance_matrix)
----> 2 ERC.solve()

~\Anaconda3\lib\site-packages\pyrb\allocation.py in solve(self)
    122 
    123     def solve(self):
--> 124         x = solve_rb_ccd(cov=self.cov)
    125         self._x = tools.to_array(x / x.sum())
    126         self.lambda_star = self.get_volatility()

~\Anaconda3\lib\site-packages\pyrb\solvers.py in solve_rb_ccd(cov, budgets, pi, c, bounds, lambda_log, _varphi)
    134     while not cvg:
    135         x, Sx, sigma_x = _cycle(
--> 136             x, c, var, _varphi, sigma_x, Sx, budgets, pi, bounds, lambda_log, cov
    137         )
    138         cvg = np.sum(np.array(x - x0) ** 2) <= CCD_COVERGENCE_TOL

SystemError: CPUDispatcher(<function _cycle at 0x000002001B982158>) returned a result with an error set

numpy version:'1.20.2'

**Comment by jcrichard** [comment]
Hi

Can you give a reproducible example with versioning please.

**Comment by nikitazhhy** [comment]
> Hi
> 
> Can you give a reproducible example with versioning please.

Hi, after updating pandas to 1.2.4, it works well, maybe it's nothing wrong with numpy.

**Comment by pedrobraz1990** [comment]
I had the same issue with pandas 1.3.3 and numpy 1.21.2

I'm contacting IT to downgrade it to 1.2.4 (which is the one I have on this other computer that works fine). Unfortunately I can't provide the example..

**Comment by vgmakeev** [comment]
Hi, the same issue with the last versions of pandas and numpy.
But it works with numpy 1.19.4, pandas 1.3.3.

**Comment by jcrichard** [comment]
The library is tested with the requirements, you can try the same packages
versions. But I will check with these updates and let you know.

**Comment by jcrichard** [comment]
@vgmakeev I do not see any issues with these versions, please look at [this colab ](https://colab.research.google.com/drive/1AbgiERC1730bXUsG9V_E7kZasA8exLiX?usp=sharing).
