### ISSUE TITLE
`quadprog` requirement

### ISSUE THREAD

**Issue by jaehyukchoi** [jcrichard/pyrb#3]
Hi,

I am very interested in testing risk parity. When installing this package, I realize that I need `quadprog` and it requires MS Visual C++. I am wondering if there's any workaround? It would be nice if I don't need to install it. Thanks.

- Jaehyuk

```
error: Microsoft Visual C++ 14.0 or greater is required. Get it with "Microsoft C++ Build Tools": https://visualstudio.microsoft.com/visual-cpp-build-tools/****
```

**Comment by jcrichard** [comment]
Hi. Not for now but only the constrained risk parity use it so you could
fork and remove the dependency. Otherwise I should switch on cvxpy but that
will make the code slower.

**Comment by jcrichard** [comment]
I close as it is not really an issue.  Btw you do not need VS14 but only [Microsoft C++ Build Tools](https://visualstudio.microsoft.com/fr/visual-cpp-build-tools/)
