### ISSUE TITLE
Negative weights?

### ISSUE THREAD

**Issue by leongache** [jcrichard/pyrb#4]
Hi, thanks for sharing and for doing reproducible research, highly appreciated.
Not an issue really, but was wondering how to achieve negative weights in the optimal solution if feasible at all? Noticed in your notebook example below and thought that weights were constrained to be less than -0.3 and -0.05, but x is all positives. So, can you explain how constraints work? I did try bounds=[-1,1] but still would never get negative weights.

C = np.array([[0,0,0,0,-1.0,-1.0,-1.0,-1.0],[1,-1,0,0,1,-1,0,0]]) 
d = [-0.3,-0.05]

CRB = ConstrainedRiskBudgeting(cov,C=C,d=d)
CRB.solve()
print(CRB)

solution x: [24.5238 28.6911  9.5175  7.2674  6.9707  7.8033  9.2305  5.9956]

**Comment by jcrichard** [comment]
Hi

Negative weights are not allowed and not feasible because of the log penalty. Besides it has been shown that the solution is not unique if negative weights are allowed. Risk parity stays a long only allocation method.

**Comment by leongache** [comment]
Thanks for such a swift reply. Understood. Can you explain how C and d params works, though? What does negative numbers mean there? or if I were to constrain weights within [0.2,1] boundaries using C and d params, how can I achieve it?

Is there any way, maybe even a tweak that you know of, to incorporate short positions? By tweak I mean if there is any easy way to translate the long only solution to the one with shorts where it's known in advance that short position is desirable in a particular asset. I might not be making sense, sorry to disturb.

**Comment by jcrichard** [comment]
C and d are the linear inequalities constraints Cx›=d where x is the weights. Just do that Cx matrix on your solution and you will understand.

I am afraid that no tweak is possible for doing long short.

**Comment by leongache** [comment]
Thanks so much
